python3 narre.py \
    --data_path /home/b.kabongo/datasets/TripAdvisor/data.csv \
    --words_embedding_path /home/b.kabongo/embeddings/glove/glove.6B.100d.txt \
    --fmt UIR \
    --train_size 0.8 \
    --test_size 0.1 \
    --val_size 0.1 \
    --embedding_size 100 \
    --id_embedding_size 128 \
    --n_factors 128 \
    --attention_size 16 \
    --kernel_sizes 3 \
    --n_filters 64 \
    --dropout_rate 0.5 \
    --max_text_length 128 \
    --max_num_review 64 \
    --batch_size 64 \
    --max_iter 50 \
    --optimizer adam \
    --learning_rate 0.001 \
    --model_selection best \
    --no-user_based \
    --trainable \
    --seed 42 \
    --user_column user_id \
    --item_column item_id \
    --rating_column rating \
    --review_column review \
    --timestamp_column timestamp \
    --no-timestamp \
    --rating_threshold 4.0 \
    --no-exclude_unknowns \
    --rmse \
    --mae \
    --no-rating_user_based \
    --ranking_k 10 \
    --no-precision \
    --no-recall \
    --no-f1 \
    --no-auc \
    --no-ndcg \
    --no-hit \
    --no-map \
    --no-mrr \
    --exp_name NARRE \
    --show_validation \
    --verbose \
    --save_dir /home/b.kabongo/exps/TripAdvisor/NARRE/